name: GitHub Metrics
on:
  schedule:
    - cron: "0 */12 * * *"   # update twice a day
  workflow_dispatch:

permissions:
  contents: write   # allow committing files

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          # Use the same PAT for API access AND for committing
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}

          filename: github-metrics.svg
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          committer_branch: main
          committer_message: "chore(metrics): update yearly contributions"
